### ISSUE TITLE
Add support for custom radio stations

### ISSUE THREAD

**Issue by JarnoVgr** [MrGreenGaming/MTA-Resources#392]
Add support for custom radio stations on top of the default radio stations.

## To-Do
- [ ] Gather radio stations.
- [ ] Create a JSON file with gathered resources.
- [ ] Create a clever UI radio station selector which overrides the default one.

## Example structure JSON file
```json
{
	"radio": [
		{
			"name": "GTA San Andreas",
			"icon": "https://example.com/img/gtasa.png",
			"radioStations": [
				{
					"name": "Playback FM",
					"internalId": 1,
					"icon": "https://example.com/img/gtasa/playbackfm.png"
				},
				{
					"name": "K-Rose",
					"internalId": 2,
					"icon": "https://example.com/img/gtasa/krose.png"
				}
			]
		},
		{
			"name": "GTA5",
			"icon": "https://example.com/img/gtav.png",
			"radioStations": [
				{
					"name": "West Coast Classics",
					"url": "https://example.com/radiostations/gtav/westcoastclassics.mp3",
					"icon": "https://example.com/img/gtav/westcoastclassics.png"
				},
				{
					"name": "Non-Stop Pop",
					"url": "https://example.com/radiostations/gtav/nonstoppop.mp3",
					"icon": "https://example.com/img/gtav/nonstoppop.png"
				}
			]
		}
	]
}
```
